'use client'

import Image from 'next/image'
import { useState } from 'react'
import { ArrowUpRight, Check, Menu, Phone, Ruler, ShieldCheck, Sparkles, X } from 'lucide-react'

const phone = '+917258951213'
const whatsapp = 'https://wa.me/917258951213'
const img = (id: string, w = 1200) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=85`
const services = [
  ['Gypsum False Ceiling','Modern gypsum ceiling designs with smooth finishing, lighting options and cove lighting for homes, offices and shops.','घर, ऑफिस और दुकान के लिए सुंदर और आधुनिक फॉल्स सीलिंग।','photo-1600607687920-4e2a09cf159d'],
  ['PVC Ceiling','Practical PVC ceiling solutions with easy maintenance and different designs for residential and commercial spaces.','आसान रखरखाव और अलग-अलग डिजाइन वाली PVC सीलिंग।','photo-1600566753190-17f0baa2a6c3'],
  ['PVC Wall Paneling','Decorative PVC wall panels in modern designs that are easy to maintain for homes, offices and shops.','दीवारों को नया और आकर्षक लुक देने के लिए PVC पैनल।','photo-1618221195710-dd6b41faaea6'],
  ['WPC Wall Paneling','Modern WPC wall panels for feature walls, TV walls, bedrooms, offices and commercial interiors.','घर और ऑफिस की दीवारों के लिए आधुनिक WPC पैनल।','photo-1600210492486-724fe5c67fb0'],
  ['WPC Fluted Panels','Clean fluted wall designs for feature walls, TV walls, living rooms, bedrooms and office interiors.','दीवारों को प्रीमियम और मॉडर्न लुक देने वाले फ्लूटेड पैनल।','photo-1600607687939-ce8a6c25118c'],
  ['Grid Ceiling','A practical ceiling choice for offices, shops and commercial spaces with easy access for maintenance.','ऑफिस, दुकान और कमर्शियल जगहों के लिए ग्रिड सीलिंग।','photo-1556761175-b413da4baf72'],
  ['Wall Partition','Room, office and shop partitions using gypsum board where suitable for clear, practical space division.','कमरे, ऑफिस या दुकान में जगह को अलग करने के लिए पार्टिशन।','photo-1497366754035-f200968a6e72'],
  ['TV Unit & Interior Work','Modern TV wall designs with WPC or fluted panels, shelving and selected interior work for your space.','TV वॉल और जरूरत के अनुसार मॉडर्न इंटीरियर का काम।','photo-1598928506311-c55ded91a20c'],
] as const
const gallery = [['False Ceiling','photo-1600607688969-a5bfcd646154'],['Gypsum Ceiling','photo-1600210491369-e753d80a41f3'],['PVC Panel','photo-1600566753086-00f18fb6b3ea'],['WPC Panel','photo-1616486338812-3dadae4b4ace'],['Fluted Panel','photo-1618220179428-22790b461013'],['Grid Ceiling','photo-1556761175-4b46a572b786']]
const wa = (service?: string) => `${whatsapp}?text=${encodeURIComponent(service ? `Hello Arbaz, I need ${service} work. I am sharing my room/site photo. Please guide me.` : 'Hello Arbaz, I am sharing my room/site photo. Please guide me with my ceiling or interior work.')}`
function Hindi({ children }: { children: React.ReactNode }) { return <span className="font-devanagari mt-1 block text-sm font-normal leading-6 text-primary">{children}</span> }
function CTA({ kind = 'whatsapp', children, service }: { kind?: 'whatsapp'|'call', children: React.ReactNode, service?: string }) { return <a href={kind === 'call' ? `tel:${phone}` : wa(service)} target={kind === 'whatsapp' ? '_blank' : undefined} rel="noreferrer" className={kind === 'call' ? 'inline-flex items-center justify-center gap-2 rounded-full border border-foreground/15 px-5 py-3 text-sm font-bold transition hover:border-primary hover:text-primary' : 'inline-flex items-center justify-center gap-2 rounded-full bg-primary px-5 py-3 text-sm font-bold text-primary-foreground shadow-lg shadow-primary/20 transition hover:-translate-y-0.5'}>{children}<ArrowUpRight data-icon="inline-end" /></a> }
function Navbar() { const [open, setOpen] = useState(false); return <header className="absolute inset-x-0 top-0 z-20"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8"><a href="#home" className="font-serif text-lg font-bold tracking-tight">FALSE CEILING <span className="text-primary">SERVICE</span></a><nav className="hidden items-center gap-8 text-sm font-medium md:flex"><a href="#home">Home</a><a href="#services">Services</a><a href="#work">Our Work</a><a href="#about">About</a><a href="#contact">Contact</a><CTA kind="call"><Phone data-icon="inline-start" /> Call Now</CTA></nav><button aria-label={open ? 'Close menu' : 'Open menu'} onClick={() => setOpen(!open)} className="rounded-full border border-foreground/10 p-2 md:hidden">{open ? <X /> : <Menu />}</button></div>{open && <nav className="mx-5 flex flex-col gap-5 rounded-2xl bg-card p-6 shadow-xl md:hidden"><a href="#home" onClick={() => setOpen(false)}>Home</a><a href="#services" onClick={() => setOpen(false)}>Services</a><a href="#work" onClick={() => setOpen(false)}>Our Work</a><a href="#about" onClick={() => setOpen(false)}>About</a><a href="#contact" onClick={() => setOpen(false)}>Contact</a><CTA kind="call"><Phone data-icon="inline-start" /> Call Now</CTA></nav>}</header> }
function Hero() { return <section id="home" className="relative overflow-hidden pt-28"><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 pb-20 lg:grid-cols-[1fr_1.05fr] lg:px-8 lg:pb-28"><div className="animate-rise"><p className="mb-5 flex items-center gap-2 text-sm font-bold uppercase tracking-[.18em] text-primary"><span className="h-px w-8 bg-primary" /> Manimajra, Chandigarh</p><h1 className="max-w-xl font-serif text-5xl leading-[1.02] tracking-tight sm:text-6xl lg:text-7xl">False Ceiling Contractor in Chandigarh<Hindi>चंडीगढ़ में फॉल्स सीलिंग और इंटीरियर का काम</Hindi></h1><p className="mt-6 max-w-lg text-lg leading-8 text-muted-foreground">Gypsum False Ceiling, PVC Ceiling, WPC Wall Paneling, Grid Ceiling and Wall Partition Services in Chandigarh.</p><div className="mt-8 flex flex-wrap gap-3"><CTA kind="call"><Phone data-icon="inline-start" /> Call Now</CTA><CTA>Send Photo on WhatsApp</CTA></div><p className="mt-6 text-sm text-muted-foreground">Serving Manimajra (Sector 13), Chandigarh and nearby areas.</p></div><div className="relative"><div className="relative aspect-[4/3] overflow-hidden rounded-[2rem] shadow-2xl"><Image src={img('photo-1600607687920-4e2a09cf159d', 1400)} alt="Modern living room with a detailed false ceiling" fill priority className="object-cover" sizes="(max-width: 1024px) 100vw, 55vw" /></div><div className="absolute -bottom-5 -left-3 rounded-2xl bg-card p-4 shadow-xl sm:-left-6"><p className="font-serif text-2xl">Simple. Clean.</p><p className="text-sm text-muted-foreground">Work that suits your space.</p></div></div></div></section> }
function SectionIntro({ eyebrow, title, hindi, copy }: { eyebrow: string, title: string, hindi?: string, copy?: string }) { return <div className="mb-10 max-w-2xl"><p className="mb-3 text-xs font-bold uppercase tracking-[.2em] text-primary">{eyebrow}</p><h2 className="font-serif text-4xl leading-tight tracking-tight sm:text-5xl">{title}{hindi && <Hindi>{hindi}</Hindi>}</h2>{copy && <p className="mt-4 text-muted-foreground leading-7">{copy}</p>}</div> }
function Services() { return <section id="services" className="bg-card py-20 lg:py-28"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionIntro eyebrow="What we do" title="Our Services" hindi="हमारी सेवाएँ" copy="Tell us what you have in mind. We will discuss the right material and finish for your room, site or shop."/><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{services.map(([name, desc, hindi, photo]) => <article key={name} className="group overflow-hidden rounded-2xl border border-border bg-background transition hover:-translate-y-1 hover:shadow-xl"><div className="relative aspect-[4/3] overflow-hidden"><Image src={img(photo, 700)} alt={`${name} interior service`} fill className="object-cover transition duration-500 group-hover:scale-105" sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 25vw" /></div><div className="flex flex-col gap-4 p-5"><h3 className="font-serif text-2xl">{name}<Hindi>{hindi}</Hindi></h3><p className="min-h-20 text-sm leading-6 text-muted-foreground">{desc}</p><div className="flex flex-wrap gap-2"><CTA kind="call">Call Now</CTA><a href={wa(name)} target="_blank" rel="noreferrer" className="inline-flex items-center rounded-full border border-primary px-4 py-2 text-xs font-bold text-primary">WhatsApp</a></div></div></article>)}</div></div></section> }
function PhotoCTA() { return <section className="px-5 py-16 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-8 rounded-[2rem] bg-foreground px-7 py-10 text-background sm:px-12 lg:flex-row lg:items-center"><div><p className="mb-3 text-xs font-bold uppercase tracking-[.2em] text-primary">Start with a photo</p><h2 className="font-serif text-4xl leading-tight sm:text-5xl">Have a Ceiling or Wall Project?<Hindi>फॉल्स सीलिंग या दीवार का काम करवाना है?</Hindi></h2><p className="mt-4 max-w-xl leading-7 text-background/70">Send us your room or site photo on WhatsApp. Tell us what you need and talk to Arbaz about your project.<span className="mt-2 block text-background/80">अपने कमरे या साइट की फोटो WhatsApp पर भेजें और अपने काम के बारे में Arbaz से बात करें।</span></p></div><a href={wa()} target="_blank" rel="noreferrer" className="inline-flex shrink-0 items-center gap-2 rounded-full bg-primary px-6 py-4 font-bold text-primary-foreground"><Sparkles data-icon="inline-start" /> Send Photo on WhatsApp</a></div></section> }
function Why() { const items = [['Quality Materials','अच्छी क्वालिटी का मटेरियल'],['Clean Finishing','साफ और अच्छी फिनिशिंग'],['Modern Designs','मॉडर्न डिजाइन'],['Professional Installation','सही तरीके से इंस्टॉलेशन'],['Direct Customer Support','सीधे हमसे संपर्क']]; return <section className="py-20 lg:py-28"><div className="mx-auto grid max-w-7xl gap-12 px-5 lg:grid-cols-[.8fr_1.2fr] lg:px-8"><SectionIntro eyebrow="Why choose us" title="Why Choose Us" hindi="हमें क्यों चुनें?" copy="We keep the process straightforward, communicate directly and focus on work that fits your requirements."/><div className="grid gap-3 sm:grid-cols-2">{items.map(([x,hindi]) => <div key={x} className="flex items-center gap-4 rounded-2xl bg-card p-5 shadow-sm"><span className="flex size-10 items-center justify-center rounded-full bg-primary/10 text-primary"><Check data-icon="inline-start" /></span><span className="font-bold">{x}<Hindi>{hindi}</Hindi></span></div>)}</div></div></section> }
function Process() { const steps = [['01','Send Your Photo','फोटो WhatsApp पर भेजें','Send your room/site photo on WhatsApp.'],['02','Tell Us Your Requirement','अपना काम बताएं','Tell Arbaz what work you need.'],['03','Site Visit / Measurement','जरूरत होने पर साइट विजिट और माप','Arrange a site visit if required.'],['04','Estimate & Work','अनुमान और काम शुरू','Discuss the estimate and proceed with the work.']]; return <section className="bg-card py-20 lg:py-28"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionIntro eyebrow="How it works" title="How It Works" hindi="काम कैसे होगा?"/><div className="grid gap-6 md:grid-cols-4">{steps.map(([num,title,hindi,copy]) => <div key={num} className="border-t-2 border-primary pt-5"><span className="font-mono text-sm text-primary">{num}</span><h3 className="mt-8 font-serif text-2xl">{title}<Hindi>{hindi}</Hindi></h3><p className="mt-3 leading-6 text-muted-foreground">{copy}</p></div>)}</div></div></section> }
function Gallery() { return <section id="work" className="py-20 lg:py-28"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionIntro eyebrow="Our work" title="Ideas for your next room." copy="These are reference images to help discuss styles and materials. Replace them with your own completed-work photos when ready."/><div className="grid grid-cols-2 gap-3 md:grid-cols-3">{gallery.map(([label, photo], i) => <div key={label} className={`group relative overflow-hidden rounded-2xl ${i === 0 ? 'col-span-2 row-span-2 aspect-square md:col-span-1' : 'aspect-[4/3]'}`}><Image src={img(photo, 900)} alt={`${label} reference interior`} fill className="object-cover transition duration-500 group-hover:scale-105" sizes="(max-width: 768px) 50vw, 33vw"/><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-foreground/80 to-transparent p-4 pt-12 text-sm font-bold text-background">{label}</div></div>)}</div></div></section> }
function Contact() { return <section id="contact" className="bg-card py-20 lg:py-28"><div className="mx-auto grid max-w-7xl gap-10 px-5 lg:grid-cols-2 lg:px-8"><div><SectionIntro eyebrow="Get in touch" title="Contact Us" hindi="हमसे संपर्क करें" copy="Share a photo or call directly. We will talk through what you need and the next step."/><div className="flex flex-col gap-5 text-lg"><p><span className="block text-sm text-muted-foreground">Name</span><strong>Arbaz</strong></p><p><span className="block text-sm text-muted-foreground">Phone / WhatsApp</span><strong>+91 7258951213</strong></p><p><span className="block text-sm text-muted-foreground">Location</span><strong>Manimajra (Sector 13), Chandigarh – 160101, India</strong><span className="mt-1 block text-sm text-primary">मनीमाजरा (सेक्टर 13), चंडीगढ़ – 160101</span></p></div><div className="mt-8 flex flex-wrap gap-3"><CTA kind="call"><Phone data-icon="inline-start" /> Call Now</CTA><CTA>WhatsApp</CTA></div></div><div className="flex min-h-80 flex-col justify-between rounded-[2rem] bg-muted p-7"><div><Ruler className="text-primary"/><h3 className="mt-8 font-serif text-3xl">Serving Manimajra</h3><p className="mt-3 max-w-sm leading-7 text-muted-foreground">Based in Sector 13, Manimajra, Chandigarh. Contact us to check service availability for your location.</p></div><div className="flex items-center gap-2 text-sm font-bold"><ShieldCheck className="text-primary" /> Direct support from Arbaz</div></div></div></section> }
export default function Site() { const jsonLd = {'@context':'https://schema.org','@type':'LocalBusiness','name':'Arbaz – False Ceiling & Interior Services','url':'https://falseceilingservice.com','telephone':'+917258951213','address':{'@type':'PostalAddress','addressLocality':'Manimajra','addressRegion':'Chandigarh','postalCode':'160101','addressCountry':'IN'},'areaServed':'Manimajra, Chandigarh'}; return <><Navbar/><main><Hero/><PhotoCTA/><Services/><Why/><Process/><Gallery/><section id="about" className="bg-primary py-20 text-primary-foreground lg:py-28"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="max-w-2xl"><p className="mb-3 text-xs font-bold uppercase tracking-[.2em] text-primary-foreground/70">About Arbaz</p><h2 className="font-serif text-4xl sm:text-5xl">About Arbaz<span className="mt-1 block font-devanagari text-sm font-normal leading-6 text-primary-foreground">Arbaz के बारे में</span></h2><p className="mt-6 text-lg leading-8 text-primary-foreground/80">Arbaz provides false ceiling and selected interior services in Manimajra, Chandigarh and nearby areas. The focus is on practical work, clean finishing and designs that suit each customer&apos;s space and requirements.</p><p className="mt-3 leading-7 text-primary-foreground/80">Arbaz मनीमाजरा, चंडीगढ़ और आसपास के क्षेत्रों में फॉल्स सीलिंग और इंटीरियर का काम करते हैं। हमारा ध्यान अच्छे काम, साफ फिनिशिंग और आपकी जरूरत के अनुसार डिजाइन पर है।</p></div></div></section><Contact/><section className="px-5 pb-28 pt-16 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-6 rounded-[2rem] border border-border bg-card p-8 text-center sm:p-12 md:flex-row md:text-left"><div><h2 className="font-serif text-3xl">Ready to show us your space?</h2><p className="mt-2 text-muted-foreground">One photo is enough to start the conversation.</p></div><CTA>Send Photo on WhatsApp</CTA></div></section></main><a href={whatsapp} target="_blank" rel="noreferrer" aria-label="Send a message on WhatsApp" className="fixed bottom-20 right-5 z-30 flex size-14 items-center justify-center rounded-full bg-primary text-primary-foreground shadow-xl md:bottom-6"><span className="text-xl font-bold">WA</span></a><div className="fixed inset-x-0 bottom-0 z-20 grid grid-cols-2 border-t border-border bg-card p-2 md:hidden"><a href={`tel:${phone}`} className="flex items-center justify-center gap-2 rounded-xl py-3 text-sm font-bold"><Phone data-icon="inline-start" /> Call Now</a><a href={whatsapp} target="_blank" rel="noreferrer" className="flex items-center justify-center gap-2 rounded-xl bg-primary py-3 text-sm font-bold text-primary-foreground">WhatsApp</a></div><script type="application/ld+json" dangerouslySetInnerHTML={{__html: JSON.stringify(jsonLd)}}/></> }
